### ISSUE TITLE
  --> programs/metaplex_core_nft_staking/src/lib.rs:13:1

### ISSUE THREAD

**Issue by SbaseTY** [krippsat/metaplex-core-staking#1]
--> programs/metaplex_core_nft_staking/src/lib.rs:13:1
   |
13 | #[program]
   | ^^^^^^^^^^
   |
   = help: message: Safety checks failed: Failed to get program path

**Comment by krippsat** [comment]
You can update solana program and anchor to fix that issues.

**Comment by krippsat** [comment]
> --> programs/metaplex_core_nft_staking/src/lib.rs:13:1 | 13 | #[program] | ^^^^^^^^^^ | = help: message: Safety checks failed: Failed to get program path

You can update solana program and anchor to fix that issues.
